# Variables
LOGIN = "akurochk"
OS = "debian/bookworm64"
# private network name, can be changed to any other name
NETWORK_NAME = "fox_net"
PROVIDER = "virtualbox"
SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"
# check 512 in school
MEMORY = 1024
CPUS = 1
SCRIPT_SERVER = "scripts/server.sh"
SCRIPT_WORKER = "scripts/worker.sh"

Vagrant.configure("2") do |config|

    # Common settings
    config.vm.box = "#{OS}"
    config.vm.box_check_update = false
    config.ssh.insert_key = false

    # Server (control-plane)
    config.vm.define "#{LOGIN}S" do |server|
        server.vm.hostname = "#{LOGIN}S"
        server.vm.network "#{NETWORK_NAME}", ip: "#{SERVER_IP}"
        server.vm.provider "#{PROVIDER}" do |v|
            v.customize ["modifyvm", :id, "--name", "#{LOGIN}S"]
            v.name = "#{LOGIN}S"
            v.memory = "#{MEMORY}"
            v.cpus = "#{CPUS}"
        end
        server.vm.provision "shell", inline: <<-SHELL
            apk update && apk add --no-cache curl bash
        SHELL
        server.vm.provision "shell", path: "#{SCRIPT_SERVER}"
    end

    # Worker (agent)
    config.vm.define "#{LOGIN}SW" do |worker|
        worker.vm.hostname = "#{LOGIN}SW"
        worker.vm.network "#{NETWORK_NAME}", ip: "#{WORKER_IP}"
        worker.vm.provider "#{PROVIDER}" do |v|
            v.customize ["modifyvm", :id, "--name", "#{LOGIN}SW"]
            v.name = "#{LOGIN}SW"
            v.memory = "#{MEMORY}"
            v.cpus = "#{CPUS}"
        end
        worker.vm.provision "shell", inline: <<-SHELL
            apk update && apk add --no-cache curl bash
        SHELL
        worker.vm.provision "shell", path: "#{SCRIPT_WORKER}"
    end

end
