# Variables
LOGIN = "akurochk"
OS = "debian/bookworm64"
NETWORK_NAME = "private_network"
PROVIDER = "virtualbox"
SERVER_IP = "192.168.56.110"
WORKER_IP = "192.168.56.111"
MEMORY = 2024
CPUS = 2
SCRIPT_SERVER = "./scripts/server.sh"
SCRIPT_WORKER = "./scripts/worker.sh"

Vagrant.configure("2") do |config|

    # Common settings
	config.vbguest.auto_update = false
    config.vm.box = "#{OS}"
    config.vm.box_check_update = false
    config.ssh.insert_key = false

    # Server (control-plane)
    config.vm.define "#{LOGIN}S" do |server|
        server.vm.hostname = "#{LOGIN}S"
        server.vm.network "#{NETWORK_NAME}", ip: "#{SERVER_IP}"
		server.vm.provider "#{PROVIDER}" do |v|
			v.name = "#{LOGIN}S"
			v.memory = MEMORY
			v.cpus = CPUS
		end
        server.vm.provision "shell", inline: <<-SHELL
            apt-get update && apt-get install -y curl bash
        SHELL
        server.vm.provision "shell", path: "#{SCRIPT_SERVER}"
    end

    # Worker (agent)
    config.vm.define "#{LOGIN}SW" do |worker|
        worker.vm.hostname = "#{LOGIN}SW"
        worker.vm.network "#{NETWORK_NAME}", ip: "#{WORKER_IP}"
		worker.vm.provider "#{PROVIDER}" do |v|
			v.name = "#{LOGIN}SW"
			v.memory = MEMORY
			v.cpus = CPUS
		end
        worker.vm.provision "shell", inline: <<-SHELL
            apt-get update && apt-get install -y curl bash
        SHELL
        worker.vm.provision "shell", path: "#{SCRIPT_WORKER}"
    end

end
