#!/bin/bash

# Set up a common Bash (shell) safety configuration:
# -e           The script immediately stops if any command returns a non-zero exit code (an error)
# -u           The script immediately stops if any variable is unset
# -o pipefail  The whole pipeline fails if any command fails. The script returns the exit code of 
#              the last command in a pipeline that failed.
set -euo pipefail
# apt-get update && apt-get install -y curl bash

# Private network IP of the K3s server
SERVER_IP="192.168.56.110"
# Private network IP of the K3s worker
WORKER_IP="192.168.56.111"
# Default shared folder location of the K3s node token
TOKEN_FILE="/vagrant/node-token"

# To install K3s agent, we need the token generated by the K3s server.
# The token is saved in a shared folder so that the worker can access it.
echo ">>> Waiting for server token..."
# Wait for server to write the token
until [ -f "${TOKEN_FILE}" ]; do
    echo "  ... token not yet available, waiting 5s"
    sleep 5
done

# Read the token from the shared folder
TOKEN=$(cat "${TOKEN_FILE}")
echo ">>> Token found. Installing K3s agent..."

# Install K3s agent
# curl -sfL https://get.k3s.io  Download the K3s installation script from the official source.
#   -s                          Silently install K3s.
#   -f                          Fail silently on server errors.
#   -L                          Follow redirects.
#   https://get.k3s.io          Official K3s installation script.
# | sh -s - agent [options]     Pipe the installation script to the shell and run it in agent mode.
#   Options:
#   --server "https://${SERVER_IP}:6443"    Specify the K3s server to connect to. 6443 = Kubernetes API server HTTPS port (standard convention).
#   --token "${TOKEN}"                      Provide the token for authentication with the server.
#   --node-ip "${WORKER_IP}"                Specify the worker (agent) node's IP address in the cluster.
#   --flannel-iface eth1                    Specify the network interface (eth1 - private network interface in Vagrant).
curl -sfL https://get.k3s.io | sh -s - agent \
    --server "https://${SERVER_IP}:6443" \
    --token "${TOKEN}" \
    --node-ip "${WORKER_IP}" \
    --flannel-iface eth1

# until systemctl is-active --quiet k3s-agent 2>/dev/null; do
#     echo "  ... still waiting"
#     sleep 5
# done

echo ">>> K3s agent installed and running."
